# .github/workflows/azure-webapps-deploy.yml
name: Build and deploy React (Vite) app to Azure Web App - silal-oday-test-app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install deps and build
        run: |
          npm install
          npm run build

      # Zip the *contents* of dist (not the dist folder itself)
      - name: Create deployment archive
        run: |
          cd dist
          zip -r ../site.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-zip
          path: site.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-zip
          path: .

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3AA329B5225B4F0A8403BAB02E97DC05 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DF3696114F4349DAAFEDD1F5E98E240C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_06791DB2E6BD4FABB945446F21272C99 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'silal-oday-test-app'
          slot-name: 'Production'
          package: site.zip   # << deploys the zip whose root is your built files
